# Generated by Django 3.2.6 on 2021-08-29 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
        ('employee', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starthour', models.TimeField(verbose_name='start hour ')),
                ('endhour', models.TimeField(verbose_name='end hour')),
                ('date', models.DateField(verbose_name='date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.role', verbose_name='role')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.location', verbose_name='location')),
            ],
        ),
    ]
